# Generated by Django 5.1.6 on 2025-02-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('male', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('birthdate', models.DateField()),
                ('jop_position', models.CharField(max_length=150)),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
