# Generated by Django 5.1.7 on 2025-04-13 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Velmart', '0003_author_category_order_book_product_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubrick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Type name of spare', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Goiteens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Type caption for your announcement ', max_length=100)),
                ('content', models.TextField(help_text='Your announcement')),
                ('price', models.DecimalField(decimal_places=2, help_text='Your price', max_digits=8)),
                ('rubrick', models.ForeignKey(help_text='Type title of your rubrick', on_delete=django.db.models.deletion.CASCADE, to='Velmart.rubrick')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Type name of machine', max_length=100)),
                ('spares', models.ManyToManyField(blank=True, help_text='Type name of spare', related_name='machines', to='Velmart.spare')),
            ],
        ),
    ]
