# Generated by Django 5.1.7 on 2025-04-27 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Velmart', '0004_rubrick_spare_goiteens_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Surname')),
                ('birthdate', models.DateField()),
                ('length_of_work', models.PositiveSmallIntegerField(verbose_name='Length of Work (years)')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Product2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('description', models.TextField(blank=True, max_length=150, null=True, verbose_name='Product Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Product Price')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Product Creation Date')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('creation_date', models.DateField(verbose_name='Creation Date')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Year')),
                ('genre', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('rate', models.FloatField()),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='Velmart.producer')),
            ],
        ),
        migrations.CreateModel(
            name='Order2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='Order Date')),
                ('status', models.CharField(choices=[('pendding', 'Waiting'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20, verbose_name='Status')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Velmart.product2', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, verbose_name='Nickname')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('favourite_movies', models.ManyToManyField(to='Velmart.movie', verbose_name='Favorite Movies')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Text your comment', max_length=500)),
                ('date', models.DateField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Velmart.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Velmart.user')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Velmart.user'),
        ),
    ]
